EXEC InsertOrMapData 
    @WinClusterID = 4,   -- Use an existing ID to map new ID to enter new ID
    @WinClusterIP = '192.168.1.4',
    @WinClusterName = 'Cluster4.stc.corp',
    @NodeID = 108,         -- Use an existing ID to map new ID to enter new ID
    @NodeIP = '192.168.1.42',
    @NodeName = 'NodeH',
    @NodeOSVersion = 'Windows Server 2019',
    @NodeComments = 'Secondary Node',
    @SQLClusterID = 1006,   -- Use an existing ID to map new ID to enter new ID
    @SQLClusterIP = '192.168.1.141',
    @SQLClusterName = 'SQLCluster6',
    @SQLType = 'Standard',
    @SQLInstanceName = 'MSSQLSERVER',
    @SQLPort = '1433',
    @SQLServerVersion = '2019',
    @NARsRaised = 'None',
    @SQLComments = 'Main SQL Cluster',
    @SQLServerEdition = 'Standard',
    @MSDTCIP = '192.168.1.4',
    @ApplicationID = 10004,  -- Use an existing ID to map new ID to enter new ID
    @AppName = 'App4',
    @AppOwner = 'vcsr',
    @AppOwnerEmail = 'vcsr@outlook.com',
    @AppVersion = '1.85.5',
    @AppDepartment = 'DIO',
    @AppComments = 'None',
    @AppCriticality = 'High';
