EXEC InsertAllData 
    @WinClusterID = 3,   -- Specify the Windows Cluster ID
    @WinClusterIP = '192.168.1.1',
    @WinClusterName = 'Cluster1',
    @NodeID = 105,         -- Specify the Node ID
    @NodeIP = '192.168.1.2',
    @NodeName = 'Node1',
    @NodeOSVersion = 'Windows Server 2019',
    @NodeComments = 'Main Node',
    @SQLClusterID = 1005,   -- Specify the SQL Cluster ID
    @SQLClusterIP = '192.168.1.3',
    @SQLClusterName = 'SQLCluster1',
    @SQLType = 'Standard',
    @SQLInstanceName = 'Instance1',
    @SQLPort = '1433',
    @SQLServerVersion = '2019',
    @NARsRaised = 'None',
    @SQLComments = 'Main SQL Cluster',
    @SQLServerEdition = 'Standard',
    @MSDTCIP = '192.168.1.4',
    @ApplicationID = 10003,  -- Specify the Application ID
    @AppName = 'MyApp',
    @AppOwner = 'Owner Name',
    @AppOwnerEmail = 'owner@example.com',
    @AppVersion = '1.0',
    @AppDepartment = 'IT',
    @AppComments = 'Test Application',
    @AppCriticality = 'High';
